
CREATE TABLE IF NOT EXISTS userdata
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    age integer NOT NULL,
    registration_date date NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT userdata_pkey PRIMARY KEY (id),
    CONSTRAINT ukjodtkq6yt6egd41yuu9d8rwur UNIQUE (email)
    )
TABLESPACE pg_default;

INSERT INTO userdata(
    id, age, registration_date, email, name)
VALUES (1,15, CURRENT_DATE, 'gmail.com', 'Test');

INSERT INTO userdata(
    id, age, registration_date, email, name)
VALUES (2,25, CURRENT_DATE, '1@gmail.com', 'Test1');

INSERT INTO userdata(
    id, age, registration_date, email, name)
VALUES (3,25, CURRENT_DATE, '2@gmail.com', 'Test2');

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO Test;
